CREATE TABLE USER (
  SEQ    INT    NOT NULL AUTO_INCREMENT,
  ID    VARCHAR(16)    NOT NULL,
  PW    VARCHAR(16)    NOT NULL,
  DEL    TINYINT(1)    DEFAULT 0,
  API_DATA    VARCHAR(128),
  API_NCLOUD    VARCHAR(128),
  ALARM_MIN    INT    NOT NULL    DEFAULT 10,
  STATION_ID     VARCHAR(9),
  MOBILE_NO     VARCHAR(9),
  ROUTE     VARCHAR(9),
  REQ_TERM    INT    NOT NULL    DEFAULT 30,
PRIMARY KEY(SEQ)
);

CREATE TABLE HISTORY (
  SEQ    INT    NOT NULL AUTO_INCREMENT,
  user_seq INT NOT NULL,
  mkTm    DATETIME NOT NULL,
  rtNm    VARCHAR(16) NOT NULL,
  stNm    VARCHAR(16) NOT NULL,
  stationNm1    VARCHAR(32),
  sec1    INT,
  n_st1    INT,
  stationNm2    VARCHAR(32),
  sec2    INT,
  n_st2    INT,
  is_last    TINYINT(1),
  delay    INT,
PRIMARY KEY(SEQ)
);
COMMIT;